# Base16 oomox-Frontier - alacritty color config
# oomox-Frontier

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x0a0a10'
foreground = '0x7b8046'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x0a0a10'
cursor = '0x7b8046'

# Normal colors
[colors.normal]
black = '0x0a0a10'
red = '0xa5685f'
green = '0x6b8551'
yellow = '0x867c41'
blue = '0x567ea9'
magenta = '0x916b97'
cyan = '0x378a83'
white = '0x7b8046'

# Bright colors
[colors.bright]
black = '0x42452b'
red = '0x867c41'
green = '0x47534e'
yellow = '0x47534e'
blue = '0x000000'
magenta = '0xefd98d'
cyan = '0x815d3c'
white = '0xefd98d'
