# Base16 oomox-Survey - alacritty color config
# oomox-Survey

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x14233a'
foreground = '0xb55944'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x14233a'
cursor = '0xb55944'

# Normal colors
[colors.normal]
black = '0x14233a'
red = '0xb65753'
green = '0x408b48'
yellow = '0x7d7d02'
blue = '0x327cbd'
magenta = '0x8c62b0'
cyan = '0x008e80'
white = '0xb55944'

# Bright colors
[colors.bright]
black = '0x643e3f'
red = '0x7d7d02'
green = '0x693f40'
yellow = '0x693f40'
blue = '0x000f26'
magenta = '0xeec399'
cyan = '0x855516'
white = '0xeec399'
[font]
size = 15
normal = { family = "proggyclean Nerd Font", style = "Regular" }
