# Base16 oomox-Puncture - alacritty color config
# oomox-Puncture

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x000000'
foreground = '0x38ba8b'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x000000'
cursor = '0x38ba8b'

# Normal colors
[colors.normal]
black = '0x000000'
red = '0xe77f6c'
green = '0x79b35d'
yellow = '0xb1a32f'
blue = '0x62a4f1'
magenta = '0xc086d8'
cyan = '0x00b1dd'
white = '0x38ba8b'

# Bright colors
[colors.bright]
black = '0x1c5d45'
red = '0xb1a32f'
green = '0x15526b'
yellow = '0x15526b'
blue = '0x000000'
magenta = '0xc5ff8c'
cyan = '0xb87d39'
white = '0xc5ff8c'
