# Base16 oomox-SlowEnd - alacritty color config
# oomox-SlowEnd

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x0d001a'
foreground = '0x6e5181'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x0d001a'
cursor = '0x6e5181'

# Normal colors
[colors.normal]
black = '0x0d001a'
red = '0x874a51'
green = '0x57662e'
yellow = '0x715d20'
blue = '0x1e6883'
magenta = '0x744f7b'
cyan = '0x036d6c'
white = '0x6e5181'

# Bright colors
[colors.bright]
black = '0x3d284d'
red = '0x715d20'
green = '0x582557'
yellow = '0x582557'
blue = '0x000006'
magenta = '0x6cb9c9'
cyan = '0x683f24'
white = '0x6cb9c9'
