# Base16 oomox-Dyson - alacritty color config
# oomox-Dyson

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x000000'
foreground = '0x3b5dc9'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x000000'
cursor = '0x3b5dc9'

# Normal colors
[colors.normal]
black = '0x000000'
red = '0xb52c3c'
green = '0x017e09'
yellow = '0xb1ad00'
blue = '0x0964c7'
magenta = '0x8b40aa'
cyan = '0x00e6e4'
white = '0x3b5dc9'

# Bright colors
[colors.bright]
black = '0x1d2e64'
red = '0xb1ad00'
green = '0x29366f'
yellow = '0x29366f'
blue = '0x000000'
magenta = '0x73eff7'
cyan = '0x9f580a'
white = '0x73eff7'
[font]
size = 15
normal = { family = "proggyclean Nerd Font", style = "Regular" }
