# Base16 oomox-Frontier - alacritty color config
[font]
normal = { family = "proggyclean Nerd Font", style = "Regular" }
size = 15
# Base16 oomox-prisonercoin-survey-complete - alacritty color config
# oomox-prisonercoin-survey-complete

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x181b22'
foreground = '0xefd98d'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x181b22'
cursor = '0xefd98d'

# Normal colors
[colors.normal]
black = '0x181b22'
red = '0xde3858'
green = '0x9fce63'
yellow = '0xccb444'
blue = '0x664ffa'
magenta = '0xca81ff'
cyan = '0x28eef0'
white = '0xefd98d'

# Bright colors
[colors.bright]
black = '0x837957'
red = '0xccb444'
green = '0x444f4c'
yellow = '0x444f4c'
blue = '0x04070e'
magenta = '0xffffd0'
cyan = '0xc1623a'
white = '0xffffd0'
